"""Wada trie executor (TDD §8.8/§8.12, gated by the M7-T1 chain verdict).

wada.generate_colorway walks the planned trie for ONE colorway: per node it
edits the PARENT node's composited image with Seedream (fal queue), then —
gate condition 1 — composites the raw output back through the step's union
mask (+2px dilation, 3px feather) IMMEDIATELY, never lazily at chain end.
Gate condition 2 guards run per node: byte-identity outside the feathered
support (lock_verified — a failure marks the colorway failed and stops that
chain; no silent bad colorways), plus ghost-fraction and in-region median
ΔE2000 logged onto the gen_nodes row.

PARALLEL-1 (2026-07-31): one task per COLORWAY, not one per run. Steps within
a colorway are inherently serial (each step edits the previous step's image),
but colorways are independent once their chains diverge, and every node is a
~39s network-bound fal call — so "generate the remaining N" fans out to N
child tasks on the wada queue and finishes in wall-clock N/concurrency time.
Two things follow, both handled here:

1. Shared prefix nodes must be paid for ONCE. Two colorways whose chains share
   a prefix would otherwise both call the model for the same node. The trie row
   IS the lock: a task INSERTs the gen_nodes row with image_key = '' (the claim
   marker) ON CONFLICT DO NOTHING — one INSERT wins, the loser polls the row and
   takes the winner's image as an ordinary §8.8 cache hit (hit_count++, $0,
   ledgered cache_hit=true). A claim whose owner died (SIGKILL/OOM: no finally
   runs) goes stale after CLAIM_STALE_S and the waiter takes it over rather than
   waiting forever. Failure paths delete their claim, so a failed node is never
   a poisoned cache entry (unchanged from M7: bad artifacts are not cached).
2. The run closes when the LAST child finishes. studies.gen_pending (migration
   0005) is decremented by every child in a finally; the child that drives it to
   zero recomputes the study's terminal status FROM THE COLORWAY ROWS and clears
   the watchdog heartbeat. No in-memory or in-broker state is trusted, and the
   recompute is idempotent, so a double decrement can only close twice.

Cache semantics (§8.8): a gen_nodes row whose image object still exists IS
the node — the model is never called for it (hit_count++, $0, ledgered with
cache_hit=true). Re-running a study therefore resumes/idempotently replays
for free. A row whose object was evicted is treated as a miss and re-filled.

Budget (§8.11): checked before EVERY model call (study cap → daily cap →
hard freeze; config in app.config). A mid-run cap marks the study 'partial'
and keeps everything generated so far — never rolled back. Every model call
is ledgered in spend_ledger with integer cents allocated cumulatively so the
study total always equals round_half_up(6.75¢ × calls) — the exact number
the estimate showed (alloc_cents docstring).

Working base: the study's base media CUTOUT (the Wada contract since the
2026-07-26 PhotoRoom decision) — ensure_cutout() before the first node,
falling back to the original when no cutout can be produced. The working
frame must equal the region-mask frame; a mismatch fails the run loudly.
When a cutout exists, its alpha also drives the residual-coverage pass
(app.wada.coverage): slot masks are grown until their union covers the whole
product silhouette, so no sliver of the ORIGINAL base colour survives the
composite; grown masks are re-uploaded content-addressed under their own sha.
The pass is deterministic pure CV, so every child of a fan-out recomputes
byte-identical grown masks — and therefore identical shas and cache keys.

Documented deviations:
- Anchored slots are painted as real chain steps (shared by every colorway).
  plan_study() excludes anchors from the assignment space, so estimates for
  anchored studies undercount by the anchor steps — flagged for M8.
- colorways.thumb_key = cw/{ws}/{colorway_id}.400.webp (§3 defines no cw
  thumb prefix; kept under cw/ so the pin/export lifecycle finds it).
- The §8.11 per-call check reads the study total per child, so N children can
  each admit one call against the same remaining headroom: a run may overshoot
  the study cap by at most (N_workers − 1) × one call (~7¢). The alternative —
  serialising the ledger behind a study-wide lock — would undo the fan-out.
- A node whose image object was evicted is regenerated by whoever notices,
  without a claim (the row is filled, so nobody would wait on it): concurrent
  children could pay twice for a re-fill. Eviction is a cold-storage event, not
  a hot path, and the ON CONFLICT DO UPDATE keeps the trie consistent.
"""

import hashlib
import io
import json
import logging
import os
import time
import urllib.request
from datetime import UTC, datetime

import numpy as np
import psycopg
from PIL import Image

from app.config import get_settings
from app.storage import get_s3
from app.wada import coverage, segmentation
from app.wada import generation as G
from app.workers import cutout
from app.workers.celery_app import celery_app

logger = logging.getLogger(__name__)

LEDGER_KIND = "edit"
RETRIES = 3  # §8.12: 3 attempts, backoff, on transport/5xx errors

# ── node claims (PARALLEL-1) ────────────────────────────────────────────────
# The claim marker is an EMPTY image_key: gen_nodes.image_key is NOT NULL and
# every other column of a claim is already known before the model call, so the
# existing table supports claiming as-is (no migration). A claim row is never a
# cache hit — readers below branch on it explicitly.
CLAIM_MARKER = ""
CLAIM_POLL_S = 2.0  # how often a waiter re-reads the claimed row
CLAIM_STALE_S = 240.0  # older than this ⇒ the owner died; take the claim over
CLAIM_ROUNDS = 6  # bounded coordination attempts per node (never hang)

BUDGET_ERROR_MARK = "budget cap (§8.11)"  # closure recognises its own message


class NodeFailed(Exception):
    """A node that must fail its colorway without retry (§8.12)."""


def _heartbeat(study_id: str) -> None:
    """Refresh the watchdog's is-a-task-alive signal (SHIP-1): the on-read
    sweep in GET /colorways only declares a run dead when this key is gone.
    One key per STUDY — every child of a fan-out refreshes it, and only the
    child that closes the run clears it. Best-effort: a redis blip must never
    kill a paid run."""
    try:
        import redis as redis_sync

        r = redis_sync.from_url(get_settings().redis_url)
        r.set(G.heartbeat_key(study_id), "1", ex=G.HEARTBEAT_TTL)
        r.close()
    except Exception:  # noqa: BLE001
        logger.warning("could not refresh generation heartbeat for %s", study_id)


def _clear_heartbeat(study_id: str) -> None:
    try:
        import redis as redis_sync

        r = redis_sync.from_url(get_settings().redis_url)
        r.delete(G.heartbeat_key(study_id))
        r.close()
    except Exception:  # noqa: BLE001
        logger.warning("could not clear generation heartbeat for %s", study_id)


def _sync_dsn() -> str:
    return get_settings().database_url.replace("+asyncpg", "")


# ── the fal boundary (tests mock THIS) ───────────────────────────────────────

def call_seedream(
    input_img: Image.Image, mask_img: Image.Image, prompt: str,
    frame: tuple[int, int],
) -> tuple[Image.Image, float]:
    """ONE Seedream edit via the fal queue (subscribe = submit + poll).
    Ported from the T1 gate scripts verbatim (endpoint, argument shape,
    dimension coercion). Returns (RGB image in `frame`, latency_s). Retries
    transport errors with backoff; never retries an unusable frame — the
    caller checks that (§8.12)."""
    import fal_client

    settings = get_settings()
    if settings.fal_api_key:
        os.environ.setdefault("FAL_KEY", settings.fal_api_key)

    def upload(img: Image.Image) -> str:
        return fal_client.upload(G.png_bytes(img), "image/png")

    last_err: Exception | None = None
    for attempt in range(RETRIES):
        t0 = time.time()
        try:
            res = fal_client.subscribe(
                G.FAL_ENDPOINT,
                arguments={
                    "prompt": prompt,
                    "image_urls": [upload(input_img), upload(mask_img)],
                    "image_size": {"width": frame[0], "height": frame[1]},
                    "num_images": 1,
                    "output_format": "png",
                    "enable_safety_checker": False,
                },
                with_logs=False,
            )
            data = urllib.request.urlopen(
                res["images"][0]["url"], timeout=120
            ).read()
            img = Image.open(io.BytesIO(data)).convert("RGB")
            latency = time.time() - t0
            if img.size != frame:
                logger.info("seedream returned %s, resizing to frame %s", img.size, frame)
                img = img.resize(frame, Image.Resampling.LANCZOS)
            return img, latency
        except Exception as e:  # noqa: BLE001 — transport/5xx: retry with backoff
            last_err = e
            logger.warning("seedream attempt %d failed: %s", attempt, e)
            time.sleep(2 * (attempt + 1))
    raise NodeFailed(f"model call failed after {RETRIES} attempts: {last_err}")


# ── budget (§8.11, checked before every call) ────────────────────────────────

def spent_today_cents(conn, workspace_id) -> int:
    (total,) = conn.execute(
        "SELECT COALESCE(SUM(cost_cents), 0) FROM spend_ledger "
        "WHERE workspace_id = %s AND occurred_at >= date_trunc('day', now())",
        (workspace_id,),
    ).fetchone()
    return int(total)


def blocked_tier(conn, workspace_id, study_actual_cents: int, next_cents: int) -> str | None:
    """None, or which cap refuses the next call: 'study' | 'daily' | 'freeze'."""
    s = get_settings()
    today = spent_today_cents(conn, workspace_id)
    if today >= s.budget_hard_freeze_cents:
        return "freeze"
    if study_actual_cents + next_cents > s.budget_study_cap_cents:
        return "study"
    if today + next_cents > s.budget_daily_cap_cents:
        return "daily"
    return None


def budget_error(tier: str) -> str:
    return f"stopped by the {tier} {BUDGET_ERROR_MARK}; partial results kept"


def ledger_call(conn, ws, study_id: str) -> int:
    """Ledger ONE model call against the study and return the cents allocated.

    §8.11's allocation is CUMULATIVE (alloc_cents: the n-th call costs whatever
    keeps the running total at round_half_up(6.75¢ × n)), so counting and
    inserting must be atomic — two children that both read "4 calls so far"
    would both allocate the 5th call's cents and the study total would stop
    reconciling with the estimate. The studies row is locked for exactly these
    two statements (no network call inside), so the fan-out is not serialised."""
    conn.commit()
    conn.execute(
        "SELECT actual_cost_cents FROM studies WHERE id = %s FOR UPDATE", (study_id,)
    ).fetchone()
    (calls_before,) = conn.execute(
        "SELECT COUNT(*) FROM spend_ledger WHERE study_id = %s AND cache_hit = false",
        (study_id,),
    ).fetchone()
    cents = G.alloc_cents(calls_before)
    conn.execute(
        "INSERT INTO spend_ledger (workspace_id, study_id, kind, model_id, "
        "cost_cents, cache_hit) VALUES (%s, %s, %s, %s, %s, false)",
        (ws, study_id, LEDGER_KIND, G.MODEL_ID, cents),
    )
    conn.execute(
        "UPDATE studies SET actual_cost_cents = actual_cost_cents + %s WHERE id = %s",
        (cents, study_id),
    )
    conn.commit()
    return cents


# ── node claims: one model call per trie node, however many tasks want it ───

def claim_node(conn, key: str, meta: dict) -> bool:
    """Atomically claim node `key` for THIS task. True = we won and must
    generate it; False = the row already exists (someone else's claim, or a
    finished node). Committed immediately so waiters can see it."""
    row = conn.execute(
        "INSERT INTO gen_nodes (cache_key, workspace_id, parent_key, depth, "
        "base_sha256, step_color_id, step_mask_sha, model_id, prompt_version, "
        "image_key, cost_cents) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 0) "
        "ON CONFLICT (cache_key) DO NOTHING RETURNING cache_key",
        (
            key, meta["ws"], meta["parent_key"], meta["depth"], meta["base_sha"],
            meta["color_id"], meta["mask_sha"], G.MODEL_ID, G.PROMPT_VERSION,
            CLAIM_MARKER,
        ),
    ).fetchone()
    conn.commit()
    return row is not None


def release_claim(conn, key: str) -> None:
    """Drop an UNFILLED claim (the node failed, was refused by the budget, or
    the task is dying). Never touches a filled node."""
    conn.execute(
        "DELETE FROM gen_nodes WHERE cache_key = %s AND image_key = %s",
        (key, CLAIM_MARKER),
    )
    conn.commit()


def await_claim(conn, key: str) -> tuple[str | None, bool]:
    """Wait for whoever claimed `key`. Returns (image_key, owned):
    (image_key, False) — the winner filled it; the caller takes a cache hit;
    (None, True)       — the claim went stale (dead owner) and is now OURS;
    (None, False)      — the claim vanished (the winner failed): reclaim.
    Never blocks longer than one stale window."""
    deadline = time.monotonic() + CLAIM_STALE_S + 2 * CLAIM_POLL_S
    waiting = False
    while time.monotonic() < deadline:
        row = conn.execute(
            "SELECT image_key, created_at < now() - make_interval(secs => %s) "
            "FROM gen_nodes WHERE cache_key = %s",
            (CLAIM_STALE_S, key),
        ).fetchone()
        conn.commit()
        if row is None:
            return None, False
        image_key, stale = row
        if image_key != CLAIM_MARKER:
            if waiting:
                logger.info("node %s filled by the claim winner; free for us", key[:12])
            return image_key, False
        if stale:
            took = conn.execute(
                "UPDATE gen_nodes SET created_at = now() "
                "WHERE cache_key = %s AND image_key = %s RETURNING cache_key",
                (key, CLAIM_MARKER),
            ).fetchone()
            conn.commit()
            if took is not None:
                logger.warning(
                    "node %s: claim stale after %.0fs — taking it over", key[:12],
                    CLAIM_STALE_S,
                )
                return None, True
        if not waiting:
            logger.info("node %s is claimed by another task; waiting", key[:12])
            waiting = True
        time.sleep(CLAIM_POLL_S)
    return None, False


def resolve_node(conn, key: str, meta: dict) -> str | None:
    """§8.8 cache lookup, made safe for concurrent colorways.

    Returns the node's image_key when the node already exists (or another task
    produced it while we waited) — the caller treats that as a cache hit — or
    None when THIS task owns the node and must pay for it."""
    for _ in range(CLAIM_ROUNDS):
        row = conn.execute(
            "SELECT image_key FROM gen_nodes WHERE cache_key = %s", (key,)
        ).fetchone()
        conn.commit()
        if row is None:
            if claim_node(conn, key, meta):
                return None  # we own it
            continue  # lost the race by a hair: wait for the winner
        if row[0] != CLAIM_MARKER:
            return row[0]  # a finished node
        image_key, owned = await_claim(conn, key)
        if owned:
            return None
        if image_key is not None:
            return image_key
        # the claim vanished (its owner failed the node): try to claim it
    logger.warning(
        "node %s: claim never resolved after %d rounds — generating it",
        key[:12], CLAIM_ROUNDS,
    )
    return None


# ── run lifecycle: the last child closes the study ──────────────────────────

def close_study(conn, study_id: str) -> str | None:
    """Recompute the study's terminal status from its colorway rows (§8.12).

    Called by the child that drives gen_pending to zero. The studies row is
    locked FOR UPDATE so simultaneous finishers serialise; the computation
    reads only the DB, so running it twice cannot produce a different answer.
    'cancelled' is never overwritten. Returns the status written, or None."""
    conn.commit()  # fresh snapshot for the lock
    row = conn.execute(
        "SELECT status, error FROM studies WHERE id = %s FOR UPDATE", (study_id,)
    ).fetchone()
    if row is None:
        conn.commit()
        return None
    error = row[1]
    rows = conn.execute(
        "SELECT status, COUNT(*) FROM colorways WHERE study_id = %s GROUP BY status",
        (study_id,),
    ).fetchall()
    counts = {r[0]: r[1] for r in rows}
    terminal = sum(counts.get(s, 0) for s in ("ready", "pinned", "rejected"))
    total = sum(counts.values())

    if error and BUDGET_ERROR_MARK in error:
        # a child hit the §8.11 cap mid-run and parked its reason on the study
        status = "partial"
    elif total and terminal == total:
        status, error = "complete", None
    elif terminal > 0:
        status, error = "partial", None
    elif counts.get("failed"):
        status, error = "failed", "all requested colorways failed"
    else:
        status, error = "partial", None
    conn.execute(
        "UPDATE studies SET status = %s, error = %s, completed_at = %s, gen_pending = 0 "
        "WHERE id = %s AND status != 'cancelled'",
        (status, error, datetime.now(UTC) if status == "complete" else None, study_id),
    )
    conn.commit()
    logger.info("study=%s run closed: %s", study_id, status)
    if status in ("complete", "partial"):
        # the exploration itself belongs on the design's development timeline,
        # not only the pins (Beezy 2026-08-03). Best-effort — closing must win.
        try:
            study_timeline_entry(conn, study_id)
        except Exception:
            logger.exception("study=%s: timeline entry failed (run stays closed)", study_id)
    return status


STUDY_ENTRY_MEDIA_MAX = 4  # lead images on the entry; the study keeps them all


def study_timeline_entry(conn, study_id: str) -> bool:
    """One timeline entry per study run: phase='study', body summarising the
    exploration, up to STUDY_ENTRY_MEDIA_MAX ready colorways attached as real
    archive media (bytes copied to src/ keys — colorway objects in cw/ are
    subject to lifecycle expiry, archive media must not be).

    Idempotent per study: the entry is keyed by (study_id, body prefix), and
    media dedupe by sha means a colorway already on the timeline (e.g. via a
    pin) is attached, not duplicated. Returns True if an entry was created."""
    row = conn.execute(
        "SELECT s.workspace_id, s.design_id, pal.name "
        "FROM studies s JOIN palettes pal ON pal.id = s.palette_id "
        "WHERE s.id = %s",
        (study_id,),
    ).fetchone()
    if row is None:
        return False
    ws, design_id, palette_name = str(row[0]), str(row[1]), row[2]

    if conn.execute(
        "SELECT 1 FROM entries WHERE study_id = %s AND phase = 'study' "
        "AND body LIKE 'Wada study%%'",
        (study_id,),
    ).fetchone():
        return False  # this run is already on the timeline

    cws = conn.execute(
        "SELECT c.image_key, c.cost_cents, p.idx "
        "FROM colorways c JOIN permutations p ON p.id = c.permutation_id "
        "WHERE c.study_id = %s AND c.status IN ('ready', 'pinned') "
        "AND c.image_key IS NOT NULL "
        "ORDER BY (c.status != 'pinned'), p.idx",
        (study_id,),
    ).fetchall()
    if not cws:
        return False
    spent = conn.execute(
        "SELECT COALESCE(SUM(cost_cents), 0) FROM colorways WHERE study_id = %s",
        (study_id,),
    ).fetchone()[0]

    body = (
        f"Wada study — {palette_name}: {len(cws)} colorway"
        f"{'' if len(cws) == 1 else 's'} ready · ${spent / 100:.2f}"
    )
    entry_id = conn.execute(
        "INSERT INTO entries (workspace_id, design_id, phase, body, study_id) "
        "VALUES (%s, %s, 'study', %s, %s) RETURNING id",
        (ws, design_id, body, study_id),
    ).fetchone()[0]

    s3 = get_s3()
    bucket = get_settings().s3_bucket
    src_url = f"/d/{design_id}/study/{study_id}"
    media_ids: list[str] = []
    for image_key, _cost, _idx in cws[:STUDY_ENTRY_MEDIA_MAX]:
        png = s3.get_object(Bucket=bucket, Key=image_key)["Body"].read()
        sha = hashlib.sha256(png).hexdigest()
        existing = conn.execute(
            "SELECT id, entry_id FROM media WHERE workspace_id = %s AND sha256 = %s",
            (ws, sha),
        ).fetchone()
        if existing is not None:
            if existing[1] is None:  # orphaned bytes — attach to this entry
                conn.execute(
                    "UPDATE media SET entry_id = %s WHERE id = %s",
                    (entry_id, existing[0]),
                )
                media_ids.append(str(existing[0]))
            continue  # already on an entry (e.g. pinned earlier) — no duplicate
        with Image.open(io.BytesIO(png)) as img:
            width, height = img.size
        media_key = f"src/{ws}/{sha}.png"
        s3.put_object(Bucket=bucket, Key=media_key, Body=png, ContentType="image/png")
        mid = conn.execute(
            "INSERT INTO media (workspace_id, entry_id, kind, r2_key, sha256, "
            "                   width, height, source_url, source_app) "
            "VALUES (%s, %s, 'image', %s, %s, %s, %s, %s, 'wada') RETURNING id",
            (ws, entry_id, media_key, sha, width, height, src_url),
        ).fetchone()[0]
        media_ids.append(str(mid))
    conn.commit()
    for mid in media_ids:  # best-effort, mirrors /media/commit
        try:
            celery_app.send_task("thumbs.generate", args=[mid])
        except Exception:  # noqa: BLE001 — broker down: backfill catches up
            logger.warning("thumbs enqueue failed for media %s", mid)
    logger.info("study=%s timeline entry created (%d media)", study_id, len(media_ids))
    return True


def finish_child(study_id: str) -> str | None:
    """Hand the baton on: decrement the run's outstanding-children counter and,
    if this was the last one, close the study and stop the heartbeat. Runs in a
    finally, so a child that raises still releases the run."""
    try:
        with psycopg.connect(_sync_dsn()) as conn:
            row = conn.execute(
                "UPDATE studies SET gen_pending = GREATEST(gen_pending - 1, 0) "
                "WHERE id = %s RETURNING gen_pending",
                (study_id,),
            ).fetchone()
            conn.commit()
            if row is None or row[0] > 0:
                return None
            status = close_study(conn, study_id)
    except Exception:  # never mask the child's own outcome with a closing error
        logger.exception("study=%s: could not close the run", study_id)
        return None
    _clear_heartbeat(study_id)
    return status


# ── per-run setup (every child re-derives it; all of it is deterministic) ────

def _prepare(study_id: str, colorway_id: str) -> dict | str:
    """Everything a colorway needs before its first node: study/colorway rows,
    slot masks in the working frame, the residual-coverage pass, the working
    base image. Returns a context dict, or a 'skipped:…' reason."""
    settings = get_settings()
    s3 = get_s3()
    bucket = settings.s3_bucket

    with psycopg.connect(_sync_dsn()) as conn:
        study = conn.execute(
            "SELECT workspace_id, base_media_id FROM studies WHERE id = %s",
            (study_id,),
        ).fetchone()
        if study is None:
            return "skipped:missing-study"
        ws, media_id = study

        target = conn.execute(
            "SELECT c.status, p.idx, p.mapping FROM colorways c "
            "JOIN permutations p ON p.id = c.permutation_id "
            "WHERE c.id = %s AND c.study_id = %s",
            (colorway_id, study_id),
        ).fetchone()
        if target is None:
            return "skipped:no-colorway"
        cw_status, perm_idx, raw_mapping = target
        if cw_status in ("ready", "pinned", "rejected"):
            return f"skipped:already-{cw_status}"
        mapping = {
            int(k): v for k, v in
            (json.loads(raw_mapping) if isinstance(raw_mapping, str) else raw_mapping).items()
        }

        slots = conn.execute(
            "SELECT idx, label, region_ids, union_mask_key, union_sha256 "
            "FROM slots WHERE study_id = %s AND kind = 'paint' ORDER BY idx",
            (study_id,),
        ).fetchall()
        if not slots:
            _fail_colorway(conn, colorway_id, "study has no paint slots")
            return "skipped:no-slots"
        slot_by_idx = {r[0]: {"label": r[1], "region_ids": r[2],
                              "mask_key": r[3], "mask_sha": r[4]} for r in slots}
        # lock slots are never painted, but their masks must take part in the
        # residual-coverage assignment below: product pixels hugging a locked
        # slot belong to the lock (stay base), not to a recolour slot
        lock_keys = [
            r[0] for r in conn.execute(
                "SELECT union_mask_key FROM slots "
                "WHERE study_id = %s AND kind = 'lock' ORDER BY idx",
                (study_id,),
            ).fetchall()
        ]

        colors = {
            r[0]: {"name": r[1], "hex": r[2].strip(), "lab": (r[3], r[4], r[5])}
            for r in conn.execute(
                "SELECT id, name, hex, lab_l, lab_a, lab_b FROM sanzo_colors "
                "WHERE id = ANY(%s)",
                (sorted(set(mapping.values())),),
            ).fetchall()
        }
        darkness = {cid: (c["lab"][0], cid) for cid, c in colors.items()}

        # per-slot min region confidence (§8.9 label fallback)
        min_conf: dict[int, float] = {}
        for idx, s in slot_by_idx.items():
            (mc,) = conn.execute(
                "SELECT MIN(confidence) FROM regions WHERE id = ANY(%s)",
                (list(s["region_ids"]),),
            ).fetchone()
            min_conf[idx] = float(mc) if mc is not None else 1.0

        media = conn.execute(
            "SELECT r2_key, sha256, seg_subject FROM media WHERE id = %s", (media_id,)
        ).fetchone()
        if media is None:
            _fail_colorway(conn, colorway_id, "study base media is missing")
            return "skipped:missing-media"
        r2_key, media_sha, seg_subject = media

    # ── working base: the CUTOUT is the Wada contract; original is fallback ──
    cutout_key = cutout.ensure_cutout(str(media_id))
    source_key = cutout_key or r2_key
    source = s3.get_object(Bucket=bucket, Key=source_key)["Body"].read()
    base_img, alpha = segmentation.working_image_and_alpha(source)
    base_png = G.png_bytes(base_img)
    base_sha = hashlib.sha256(base_png).hexdigest()
    frame = base_img.size
    logger.info("study=%s base=%s sha=%s frame=%s", study_id, source_key,
                base_sha[:12], frame)

    # slot masks, verified against the working frame
    slot_mask: dict[int, np.ndarray] = {}
    for idx, s in slot_by_idx.items():
        png = s3.get_object(Bucket=bucket, Key=s["mask_key"])["Body"].read()
        arr = np.asarray(Image.open(io.BytesIO(png)).convert("L")) > 127
        if arr.shape != (frame[1], frame[0]):
            raise RuntimeError(
                f"mask frame {arr.shape} disagrees with working frame {frame} — "
                "masks and base must share the 1536 frame"
            )
        slot_mask[idx] = arr

    # ── residual coverage (the base-colour leak fix): the cutout's alpha is
    # the ground-truth product silhouette. Coarse polygons + per-region
    # refinement leave product slivers outside EVERY slot union, and the
    # §8.10 composite would keep the ORIGINAL base colour there. Assign each
    # uncovered silhouette component to the nearest slot — locks included, so
    # a sliver hugging a locked slot stays unpainted rather than being
    # swallowed by a recolour slot. Deterministic pure CV, so replays (and the
    # sibling children of a fan-out) grow identical masks; each grown mask
    # re-enters the content-addressed union key space under the sha of its
    # ACTUAL bytes, keeping gen_nodes cache keys true to the pixels painted
    # (§8.8) — and keeping siblings on the SAME keys, so the trie is shared.
    # No cutout (alpha is None, the original-image fallback) → no silhouette
    # ground truth → unchanged masks.
    if alpha is not None and slot_mask:
        cover_in: dict[tuple[int, int], np.ndarray] = {
            (0, idx): m for idx, m in slot_mask.items()
        }
        for j, lk in enumerate(lock_keys):
            png = s3.get_object(Bucket=bucket, Key=lk)["Body"].read()
            arr = np.asarray(Image.open(io.BytesIO(png)).convert("L")) > 127
            if arr.shape != (frame[1], frame[0]):
                raise RuntimeError(
                    f"lock mask frame {arr.shape} disagrees with working frame {frame} — "
                    "masks and base must share the 1536 frame"
                )
            cover_in[(1, j)] = arr
        covered, cov = coverage.cover_silhouette(alpha, cover_in)
        # GUARD v2 (2026-08-06): the model reports what it SAW (media.seg_subject).
        # single-product → the whole silhouette IS the garment: always fill.
        # worn-on-model / multiple-items → never fill (skin/other items must
        # not be recolored). Legacy scans (NULL) keep the 30%-residual rule.
        residual_frac = cov.residual_px / max(int(alpha.sum()), 1)
        skip_fill = (
            seg_subject in ("worn-on-model", "multiple-items")
            or (seg_subject is None and residual_frac > 0.30)
        )
        if skip_fill and cov.residual_px:
            logger.warning(
                "study=%s residual %.0f%% + subject=%s — skipping coverage "
                "growth (regions only, no fill-in)",
                study_id, residual_frac * 100, seg_subject,
            )
            cov = cov.__class__(residual_px=0, n_components=0,
                                added_px={k: 0 for k in cov.added_px})
        for idx in slot_mask:
            if cov.added_px[(0, idx)] == 0:
                continue
            grown = covered[(0, idx)]
            png = G.mask_png_bytes(grown)
            sha = hashlib.sha256(png).hexdigest()
            s3.put_object(
                Bucket=bucket, Key=f"mask/{ws}/{media_sha}/union/{sha}.png",
                Body=png, ContentType="image/png",
            )
            slot_mask[idx] = grown
            slot_by_idx[idx]["mask_sha"] = sha
        if cov.residual_px:
            logger.info(
                "study=%s residual coverage: %d px in %d components assigned "
                "(%.4f of silhouette)",
                study_id, cov.residual_px, cov.n_components,
                cov.residual_px / max(int(alpha.sum()), 1),
            )

    # distinct step masks: single-slot steps reuse the slot union sha; multi-
    # slot steps (a colour shared by slots) union on the fly and upload to the
    # §3 union key so the sha is durable and shareable across studies
    step_masks: dict[tuple[int, ...], tuple[np.ndarray, str]] = {}

    def step_mask(slot_idxs: tuple[int, ...]) -> tuple[np.ndarray, str]:
        if slot_idxs in step_masks:
            return step_masks[slot_idxs]
        if len(slot_idxs) == 1:
            got = (slot_mask[slot_idxs[0]], slot_by_idx[slot_idxs[0]]["mask_sha"])
        else:
            union = slot_mask[slot_idxs[0]].copy()
            for i in slot_idxs[1:]:
                union |= slot_mask[i]
            png = G.mask_png_bytes(union)
            sha = hashlib.sha256(png).hexdigest()
            key = f"mask/{ws}/{media_sha}/union/{sha}.png"
            s3.put_object(Bucket=bucket, Key=key, Body=png, ContentType="image/png")
            got = (union, sha)
        step_masks[slot_idxs] = got
        return got

    return {
        "ws": ws, "base_img": base_img, "base_sha": base_sha, "frame": frame,
        "slot_by_idx": slot_by_idx, "min_conf": min_conf, "colors": colors,
        "darkness": darkness, "mapping": mapping, "perm_idx": perm_idx,
        "step_mask": step_mask, "s3": s3, "bucket": bucket,
    }


def _fail_colorway(conn, colorway_id: str, error: str) -> None:
    conn.execute(
        "UPDATE colorways SET status = 'failed', error = %s WHERE id = %s "
        "AND status NOT IN ('ready', 'pinned', 'rejected')",
        (error, colorway_id),
    )
    conn.commit()


# ── the executor: ONE colorway per task ──────────────────────────────────────

@celery_app.task(name="wada.generate_colorway")
def generate_colorway(study_id: str, colorway_id: str) -> str:
    """One colorway's chain. Dispatched once per colorway by the enqueue site
    (app.routers.generation._enqueue) — N of these run concurrently on the wada
    queue and coordinate through the trie and studies.gen_pending."""
    _heartbeat(study_id)  # the watchdog must see a live task from second one
    try:
        return _generate_colorway(study_id, colorway_id)
    finally:
        finish_child(study_id)


def _generate_colorway(study_id: str, colorway_id: str) -> str:
    ctx = _prepare(study_id, colorway_id)
    if isinstance(ctx, str):
        logger.info("study=%s colorway=%s %s", study_id, colorway_id, ctx)
        return ctx

    ws = ctx["ws"]
    s3, bucket = ctx["s3"], ctx["bucket"]
    base_img, base_sha, frame = ctx["base_img"], ctx["base_sha"], ctx["frame"]
    colors, slot_by_idx, min_conf = ctx["colors"], ctx["slot_by_idx"], ctx["min_conf"]
    step_mask = ctx["step_mask"]
    steps = G.chain_steps(ctx["mapping"], ctx["darkness"])

    node_imgs: dict[str, Image.Image] = {}  # in-run memo
    stop: str | None = None  # 'budget:<tier>' | 'cancelled'
    fail: str | None = None

    with psycopg.connect(_sync_dsn()) as conn:
        conn.execute(
            "UPDATE colorways SET status = 'generating', error = NULL, "
            "generation_started_at = now() WHERE id = %s",
            (colorway_id,),
        )
        conn.commit()

        parent = base_img
        chain: list[tuple[str, str]] = []
        touched = np.zeros((frame[1], frame[0]), bool)
        new_cents = hits = 0
        t0 = time.time()

        for color_id, slot_idxs in steps:
            _heartbeat(study_id)  # watchdog: still alive, one key per study
            # cancellation is checked between nodes (§8.12)
            (st,) = conn.execute(
                "SELECT status FROM studies WHERE id = %s", (study_id,)
            ).fetchone()
            conn.commit()
            if st == "cancelled":
                stop = "cancelled"
                break

            mask, mask_sha = step_mask(slot_idxs)
            color = colors[color_id]
            chain.append((color["hex"], mask_sha))
            key = G.cache_key(base_sha, chain)
            meta = {
                "ws": ws,
                "parent_key": G.cache_key(base_sha, chain[:-1]) if len(chain) > 1 else None,
                "depth": len(chain), "base_sha": base_sha,
                "color_id": color_id, "mask_sha": mask_sha,
            }

            # ── §8.8 cache / claim: is this node already ours to skip? ──────
            cached = node_imgs.get(key)
            owned = False
            if cached is None:
                node_image_key = resolve_node(conn, key, meta)
                owned = node_image_key is None
                if node_image_key is not None:
                    try:
                        obj = s3.get_object(Bucket=bucket, Key=node_image_key)["Body"].read()
                        cached = Image.open(io.BytesIO(obj)).convert("RGB")
                    except Exception:  # noqa: BLE001 — evicted object = cache miss
                        logger.info("node %s object evicted; regenerating", key[:12])
                        cached = None
            if cached is not None:
                conn.execute(
                    "UPDATE gen_nodes SET hit_count = hit_count + 1, "
                    "last_used_at = now() WHERE cache_key = %s",
                    (key,),
                )
                conn.execute(
                    "INSERT INTO spend_ledger (workspace_id, study_id, kind, "
                    "model_id, cost_cents, cache_hit) "
                    "VALUES (%s, %s, %s, %s, 0, true)",
                    (ws, study_id, LEDGER_KIND, G.MODEL_ID),
                )
                conn.commit()
                node_imgs[key] = cached
                parent = cached
                touched |= G.touched_support(mask)
                hits += 1
                continue

            # §8.11 check #3: before EVERY model call. The price of the next
            # call is read without a lock (siblings may be ledgering at the same
            # moment) — it is a 6.75¢-vs-7¢ difference on a cap check, and the
            # exact allocation is settled by ledger_call() after the call.
            (calls_before,) = conn.execute(
                "SELECT COUNT(*) FROM spend_ledger "
                "WHERE study_id = %s AND cache_hit = false",
                (study_id,),
            ).fetchone()
            next_cents = G.alloc_cents(calls_before)
            (study_actual,) = conn.execute(
                "SELECT actual_cost_cents FROM studies WHERE id = %s", (study_id,)
            ).fetchone()
            tier = blocked_tier(conn, ws, study_actual, next_cents)
            conn.commit()
            if tier is not None:
                if owned:
                    release_claim(conn, key)
                conn.execute(
                    "UPDATE colorways SET status = 'planned' WHERE id = %s",
                    (colorway_id,),
                )
                # park the reason on the study; the child that closes the run
                # turns it into the 'partial' verdict (status stays 'generating'
                # while siblings are still painting)
                conn.execute(
                    "UPDATE studies SET error = %s WHERE id = %s AND status = 'generating'",
                    (budget_error(tier), study_id),
                )
                conn.commit()
                stop = f"budget:{tier}"
                break

            labels = [slot_by_idx[i]["label"] for i in slot_idxs]
            phrase = G.region_phrase(labels, min(min_conf[i] for i in slot_idxs))
            prompt = G.build_prompt(phrase, color["name"], color["hex"])
            try:
                raw, latency = call_seedream(
                    parent, Image.fromarray(mask.astype(np.uint8) * 255, "L"),
                    prompt, frame,
                )
            except NodeFailed as e:
                release_claim(conn, key)
                fail = str(e)
                break
            except BaseException:  # a dying worker must not leave a live claim
                release_claim(conn, key)
                raise
            if G.unusable(raw):
                release_claim(conn, key)
                fail = "model returned an unusable frame (uniform image)"
                break

            comp, untouched = G.composite_step(parent, raw, mask)
            lock = G.verify_lock(comp, parent, untouched)
            ghost = G.ghost_fraction(comp, base_img, mask)
            de_in = G.in_region_delta_e(comp, mask, color["lab"])
            if ghost > G.GHOST_ALERT:
                logger.warning(
                    "study=%s node=%s ghost fraction %.3f > %.2f (alert only)",
                    study_id, key[:12], ghost, G.GHOST_ALERT,
                )

            # money was spent whether or not the node is usable: ledger it
            cents = ledger_call(conn, ws, study_id)
            new_cents += cents

            if not lock:
                # gate condition 2: P1 — no silent bad colorways, and the
                # node is NOT cached (a later run must not reuse it)
                logger.error(
                    "study=%s node=%s LOCK ASSERT FAILED — chain stopped",
                    study_id, key[:12],
                )
                conn.commit()
                release_claim(conn, key)
                fail = "lock_verified assertion failed (P1: composite touched locked pixels)"
                break

            image_key = f"node/{ws}/{key}.png"
            s3.put_object(
                Bucket=bucket, Key=image_key, Body=G.png_bytes(comp),
                ContentType="image/png",
            )
            # fills our claim row (or inserts the node outright when the claim
            # was lost to eviction/timeout) — either way the trie ends up true
            conn.execute(
                "INSERT INTO gen_nodes (cache_key, workspace_id, parent_key, "
                "depth, base_sha256, step_color_id, step_mask_sha, model_id, "
                "prompt_version, image_key, cost_cents, lock_verified, "
                "ghost_fraction, delta_e_in, latency_ms) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) "
                "ON CONFLICT (cache_key) DO UPDATE SET image_key = EXCLUDED.image_key, "
                "cost_cents = EXCLUDED.cost_cents, "
                "lock_verified = EXCLUDED.lock_verified, "
                "ghost_fraction = EXCLUDED.ghost_fraction, "
                "delta_e_in = EXCLUDED.delta_e_in, "
                "latency_ms = EXCLUDED.latency_ms, last_used_at = now()",
                (
                    key, ws, meta["parent_key"], len(chain), base_sha, color_id,
                    mask_sha, G.MODEL_ID, G.PROMPT_VERSION, image_key, cents, lock,
                    ghost, de_in, int(latency * 1000),
                ),
            )
            conn.commit()
            node_imgs[key] = comp
            parent = comp
            touched |= ~untouched

        if stop == "cancelled":
            conn.execute(
                "UPDATE colorways SET status = 'planned' WHERE id = %s "
                "AND status = 'generating'",
                (colorway_id,),
            )
            conn.commit()
            return "stopped:cancelled"
        if stop:
            return f"stopped:{stop}"
        if fail is not None:
            conn.execute(
                "UPDATE colorways SET status = 'failed', error = %s, "
                "cost_cents = cost_cents + %s, cache_hits = %s, "
                "lock_verified = false, model_id = %s WHERE id = %s",
                (fail, new_cents, hits, G.MODEL_ID, colorway_id),
            )
            conn.commit()
            logger.warning("study=%s colorway=%s failed: %s", study_id, colorway_id, fail)
            return "failed:1"

        # leaf: the whole-chain §8.10 assertion vs the BASE, then persist
        final_lock = bool(
            np.array_equal(
                np.asarray(parent.convert("RGB"))[~touched],
                np.asarray(base_img.convert("RGB"))[~touched],
            )
        )
        cw_key = f"cw/{ws}/{colorway_id}.png"
        s3.put_object(Bucket=bucket, Key=cw_key, Body=G.png_bytes(parent),
                      ContentType="image/png")
        thumb = parent.copy()
        thumb.thumbnail((400, 400), Image.Resampling.LANCZOS)
        buf = io.BytesIO()
        thumb.save(buf, format="WEBP", quality=82)
        thumb_key = f"cw/{ws}/{colorway_id}.400.webp"
        s3.put_object(Bucket=bucket, Key=thumb_key, Body=buf.getvalue(),
                      ContentType="image/webp")
        conn.execute(
            "UPDATE colorways SET status = 'ready', image_key = %s, "
            "thumb_key = %s, model_id = %s, cost_cents = %s, cache_hits = %s, "
            "lock_verified = %s, latency_ms = %s, error = NULL WHERE id = %s",
            (cw_key, thumb_key, G.MODEL_ID, new_cents, hits, final_lock,
             int((time.time() - t0) * 1000), colorway_id),
        )
        conn.commit()
        logger.info(
            "study=%s colorway=%s (perm %d) ready: %d¢, %d cache hits, lock=%s",
            study_id, colorway_id, ctx["perm_idx"], new_cents, hits, final_lock,
        )
        return "done:1"
