from playwright.sync_api import sync_playwright, expect
from fixtures import Fixture, BASE, EVIDENCE

with sync_playwright() as pw:
    browser = pw.chromium.launch()
    for width in [320, 390, 1440]:
        f = Fixture()
        f.designs.extend(dict(f.designs[0], id=f'extra{i}', index_no=i, name=f'Coat {i:02}', created_at=f'2026-09-{i % 28 + 1:02}T12:00:00Z') for i in range(4, 44))
        ctx, page = f.context(browser, width, 844)
        page.goto(BASE + '/p/p1')
        page.get_by_role('button', name='List', exact=True).click()
        page.get_by_label('Sort archive').select_option('name')
        page.get_by_label('Search archive').fill('coat')
        expect(page.locator('#dgrid')).to_have_class('dgrid archive-list')
        expect(page.locator('#dgrid .dname').first).to_have_text('Coat 04')
        page.get_by_label('Search archive').fill('no-such-design')
        expect(page.get_by_text('No matching designs. Try another search or filter.')).to_be_visible()
        page.get_by_label('Search archive').fill('coat')
        page.locator('#dgrid .dcard').filter(has_text='Coat 25').click()
        expect(page).to_have_url(BASE + '/d/extra25')
        page.locator('.panel-actions').get_by_role('button', name='Back', exact=True).click()
        expect(page.locator('#dgrid')).to_have_class('dgrid archive-list')
        expect(page.get_by_label('Search archive')).to_have_value('coat')
        page.wait_for_timeout(250)
        assert page.evaluate('scrollY') > 500
        position = page.evaluate('scrollY')
        page.locator('#dgrid .dcard').filter(has_text='Coat 25').click()
        page.go_back()
        page.wait_for_timeout(250)
        assert abs(page.evaluate('scrollY') - position) < 3
        page.get_by_role('button', name='Top', exact=True).click()
        page.wait_for_timeout(500)
        assert page.evaluate('scrollY') == 0
        assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
        page.screenshot(path=str(EVIDENCE / f'archive-list-{width}.png'))
        page.get_by_role('button', name='Grid', exact=True).click()
        expect(page.locator('#dgrid')).to_have_class('dgrid')
        page.get_by_label('Search archive').fill('')
        page.get_by_label('Sort archive').select_option('number')
        expect(page.locator('#dgrid .dname').first).to_have_text('First coat')
        page.get_by_label('Sort archive').select_option('recent')
        expect(page.locator('#dgrid .dname').first).to_have_text('Coat 27')
        page.locator('#status-chips [data-f=final]').click()
        page.locator('#dgrid .dcard').filter(has_text='Coat 27').click()
        page.locator('.panel-actions').get_by_role('button', name='Back', exact=True).click()
        expect(page.locator('#status-chips [data-f=final]')).to_have_class('chip on')
        page.goto(BASE + '/')
        page.get_by_role('button', name='List', exact=True).click()
        page.get_by_label('Search archive').fill('second')
        page.get_by_label('Sort archive').select_option('name')
        page.locator('.project-list').get_by_text('Second collection', exact=True).click()
        expect(page.get_by_label('Search archive')).to_have_value('')
        expect(page.get_by_role('button', name='Grid', exact=True)).to_have_attribute('aria-pressed', 'true')
        # Archive destination resumes Home's view/search instead of resetting it.
        page.locator('.tabbar' if width < 900 else '.side-nav').get_by_role('button' if width < 900 else 'link', name='Archive', exact=True).click()
        expect(page.get_by_label('Search archive')).to_have_value('second')
        expect(page.get_by_role('button', name='List', exact=True)).to_have_attribute('aria-pressed', 'true')
        assert not f.errors, f.errors
        assert not f.unhandled, f.unhandled
        f.save(EVIDENCE / f'archive-browse-{width}.json')
        ctx.close()
    f = Fixture()
    f.projects.extend(dict(id=f'p{i}', name=f'Project {i:02}', kicker='TEST', design_count=0) for i in range(4, 40))
    ctx, page = f.context(browser, 390, 844)
    page.goto(BASE + '/')
    page.get_by_role('button', name='List', exact=True).click()
    page.locator('.project-list').get_by_text('Project 25', exact=True).click()
    page.locator('.tabbar').get_by_role('button', name='Archive', exact=True).click()
    page.wait_for_timeout(250)
    assert page.evaluate('scrollY') > 500
    expect(page.get_by_role('button', name='List', exact=True)).to_have_attribute('aria-pressed', 'true')
    assert not f.errors, f.errors
    ctx.close()
    browser.close()
print('PASS Grid/List, search/no-match, Name/Number/Recent, return scroll, per-project isolation, Archive state at 320/390/1440')
